### PR TITLE
EZP-24138: Fix eZ Tags missing schema sql required for multilanguage postgresql support

### PR DESCRIPTION
**Pull request by brookinsconsulting**
Hello,

We noticed that the activity on PR #90 had gone stale for some time and since we have already been very active in that PR we wanted to step up and try to complete the work required.

This is the related issue ticket: https://jira.ez.no/browse/EZP-24138

This PR is specifically for the multilanguage branch. We have submitted another PR #91 for the required changes to the master branch as well.

This PR comes from the following share.ez.no forum conversation: http://share.ez.no/forums/install-configuration/migration-from-mysql-to-postgresql#comment85594

Please let us know what you think!

Cheers,
Brookins Consulting

### CODE REVIEW

**Comment by emodric** [comment]
Hi @brookinsconsulting,

Thanks for this :)

Two issues (again) :)

1) CS fix: No new line at EOF

2) `eztags_keyword_s` sequence is not needed, right? It's not being used in `eztags_keyword` table.

**Comment by brookinsconsulting** [comment]
Hello @emodric

We have addressed the two issues you mentioned and flattened.

Please let us know what you think.

Cheers,
Brookins Consulting

**Comment by emodric** [comment]
Merging :)

Thanks @brookinsconsulting!

**Comment by brookinsconsulting** [comment]
Hello @emodric

Thank you very much for your prompt review and merging!

The real thanks goes to @Ramna who did the real work and testing.

We just finished up the remaining PR work.

We are very happy that all of us can now say we have postgresql support in eztags!

Thanks again. Take it eZ!

Cheers,
Brookins Consulting

**Pull request merged**
