### PR TITLE
EZP-24138: Fix eZ Tags missing schema sql required for postgresql support

### PR DESCRIPTION
**Pull request by Ramna**
https://jira.ez.no/browse/EZP-24138

### CODE REVIEW

**Comment by brookinsconsulting** [comment]
+1 Great job @Ramna this PR looks like you did the 'work' correctly this time, congratulations. 3rd times the charm ehh ;)  ping @andrerom

**Comment by Ramna** [comment]
Yeah finally ;) and all the credit goes to Heath who helped me through all the process! Thanks for your patience :)

**Comment by emodric** [comment]
Hey @Ramna!

Thanks for this and good job! Also thanks to @brookinsconsulting for helping with PR!

However, you've created the pull request against the wrong branch. It should've been created against the `master` branch and not `multilanguage` (in case you didn't notice, SQL schema differs between the two branches)

**Comment by brookinsconsulting** [comment]
@emodric 

I think Heath (in share forums) got confused (at least a little) with your request for PR to the multilingual branch, https://github.com/ezsystems/eztags/pull/85#issuecomment-72425868

We now understand that we basically need PRs for both and that the multilingual sql for postgresql needs to match the unique schema already in place with the mysql version.

@Ramna 

I'm certain now that we are that much closer to solving this issue once and for all.

Would you be willing to do the work (double now*) to re-submit your current postgresql schema.sql file to the master branch. You would need to use Heath's instructions but replace branch name multilingual with master. If you need Heath to re-write the instructions specific for master, just ask in the forums, he will help you.

Also would you be willing to refactor your current postgresql schema.sql file to match the custom / newer / different mysql schema.sql file in the multilingual branch and simply repeat the instructions Heath gave you to use to submit the required improvements?

Best wishes

Cheers,
Brookins Consulting

**Comment by emodric** [comment]
@brookinsconsulting Thanks for the great explanation and helping @Ramna and me with the pull request! :+1:

@Ramna Don't forget to include [the `priority` column](https://github.com/ezsystems/eztags/blob/master/sql/mysql/schema.sql#L22) in `eztags_attribute_link` table which was added recently.

**Comment by emodric** [comment]
Closing, replaced by #91 & #92.

**Pull request closed without merging**
