### PR TITLE
Added eztags tree menu to edit view

### PR DESCRIPTION
**Pull request by thiagocamposviana**
Now it is properly checking for the hide root setting and also for the max tags setting.

Right now I am showing an alert message:

"Limit reached"

We can decide what to do when max $ of tags has been reached.

### CODE REVIEW

**Comment by masev** [comment]
@emodric did you remove this feature from version 2 ? Any reason ?
Thanks

**Comment by emodric** [comment]
@masev It was never ported to version 2.0.

**Comment by emodric** [comment]
@masev I will soon be releasing 2.1 which has a rewriten jquery.eztags.js so current implementation wouldn't work anyway.

**Comment by masev** [comment]
Ok thanks

**Pull request merged**
