### PR TITLE
EZP-24138: Fix eZ Tags missing schema sql required for postgresql support

### PR DESCRIPTION
**Pull request by brookinsconsulting**
Hello,

We noticed that the activity on PR #90 had gone stale for some time and since we have already been very active in that PR we wanted to step up and try to complete the work required.

This is the related issue ticket: https://jira.ez.no/browse/EZP-24138

This PR is specifically for the master branch. We will submit another PR for the required changes to the multilingual branch as well.

This PR comes from the following share.ez.no forum conversation: http://share.ez.no/forums/install-configuration/migration-from-mysql-to-postgresql#comment85594

Please let us know what you think!

Cheers,
Brookins Consulting

### CODE REVIEW

**Comment by emodric** [comment]
Nice one @brookinsconsulting, thanks!

Two issues:

1) One small CS issue: no new line at the end of file

2) There's no [`priority` column (https://github.com/ezsystems/eztags/blob/master/sql/mysql/schema.sql#L22) in `eztags_attribute_link` table which was added recently.

**Comment by brookinsconsulting** [comment]
Hello @emodric 

We have addressed the two issues you mentioned and flattened.

Please let us know what you think.

Cheers,
Brookins Consulting

**Comment by emodric** [comment]
Thanks @brookinsconsulting!

Just one small issue: `priority` column should be after `object_id`, not before.

**Comment by brookinsconsulting** [comment]
Hello @emodric

We have addressed the issue you mentioned and flattened.

Please let us know what you think.

Cheers,
Brookins Consulting

**Comment by emodric** [comment]
Thanks @brookinsconsulting, merging!

**Comment by brookinsconsulting** [comment]
Hello @emodric

Thank you very much for your prompt review and merging!

The real thanks goes to @Ramna who did the real work and testing.

We just finished up the remaining PR work.

We are very happy that all of us can now say we have master postgresql support in eztags!

Thanks again. Take it eZ!

Cheers,
Brookins Consulting

**Pull request merged**
